-- SmartBiz schema for Supabase (PostgreSQL). Paste into Supabase > SQL Editor > Run.
-- Tables match app/models.py, so the FastAPI backend works against it unchanged.

-- ---------- Tables ----------
create table if not exists public.users (
  id integer generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null unique,
  password_hash text not null,
  role varchar(20) not null default 'staff' check (role in ('admin', 'staff'))
);

create table if not exists public.customers (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(30) not null default '',
  city varchar(80) not null default ''
);

create table if not exists public.suppliers (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  phone varchar(30) not null default '',
  item varchar(200) not null default ''
);

create table if not exists public.products (
  id integer generated by default as identity primary key,
  name varchar(120) not null,
  sku varchar(40) not null unique,
  stock integer not null default 0 check (stock >= 0),          -- stock can never go negative
  reorder_level integer not null default 0 check (reorder_level >= 0),
  price numeric(12,2) not null default 0 check (price >= 0)
);

create table if not exists public.expenses (
  id integer generated by default as identity primary key,
  title varchar(160) not null,
  category varchar(60) not null default 'General',
  amount numeric(12,2) not null check (amount > 0),
  date date not null default current_date
);

create table if not exists public.orders (
  id integer generated by default as identity primary key,
  customer_id integer not null references public.customers(id) on delete restrict,
  stage smallint not null default 0 check (stage between 0 and 4),  -- New..Delivered
  total numeric(12,2) not null default 0 check (total >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete cascade,
  product_id integer not null references public.products(id) on delete restrict,
  qty integer not null check (qty > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0)
);

create table if not exists public.payments (
  id integer generated by default as identity primary key,
  order_id integer not null references public.orders(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  note varchar(120) not null default '',
  paid_at timestamptz not null default now()
);

create index if not exists idx_orders_customer on public.orders(customer_id);
create index if not exists idx_orders_created on public.orders(created_at);
create index if not exists idx_items_order on public.order_items(order_id);
create index if not exists idx_items_product on public.order_items(product_id);
create index if not exists idx_payments_order on public.payments(order_id);
create index if not exists idx_expenses_date on public.expenses(date);

-- ---------- Safety net: payments can never exceed the order total ----------
create or replace function public.check_payment_limit() returns trigger
language plpgsql as $$
declare ord_total numeric; already numeric;
begin
  select total into ord_total from public.orders where id = new.order_id for update;
  select coalesce(sum(amount), 0) into already
    from public.payments where order_id = new.order_id and id is distinct from new.id;
  if already + new.amount > ord_total then
    raise exception 'Payment exceeds the pending amount for order %', new.order_id using errcode = '23514';
  end if;
  return new;
end $$;

drop trigger if exists trg_payment_limit on public.payments;
create trigger trg_payment_limit before insert or update on public.payments
  for each row execute function public.check_payment_limit();

-- ---------- Views for the dashboard and AI questions ----------
create or replace view public.order_balances with (security_invoker = true) as
select o.id, 'ORD-' || (1000 + o.id) as code, o.customer_id, c.name as customer, o.stage, o.total,
       coalesce(sum(p.amount), 0) as paid,
       o.total - coalesce(sum(p.amount), 0) as pending,
       o.created_at
from public.orders o
join public.customers c on c.id = o.customer_id
left join public.payments p on p.order_id = o.id
group by o.id, c.name;

create or replace view public.customer_dues with (security_invoker = true) as
select c.id, c.name, coalesce(sum(b.pending), 0) as due
from public.customers c
left join public.order_balances b on b.customer_id = c.id
group by c.id;

create or replace view public.low_stock with (security_invoker = true) as
select id, name, sku, stock, reorder_level from public.products where stock <= reorder_level;

-- ---------- Security ----------
-- FastAPI connects with the database owner role (bypasses RLS). Turning RLS on with no policies
-- means Supabase's public REST/anon keys cannot read or write any business data directly.
alter table public.users       enable row level security;
alter table public.customers   enable row level security;
alter table public.suppliers   enable row level security;
alter table public.products    enable row level security;
alter table public.expenses    enable row level security;
alter table public.orders      enable row level security;
alter table public.order_items enable row level security;
alter table public.payments    enable row level security;

-- Read-only role for the AI Q&A layer. It can see business data but never the users table
-- and cannot change anything. CHANGE THE PASSWORD before running.
do $$ begin
  if not exists (select from pg_roles where rolname = 'smartbiz_ai') then
    create role smartbiz_ai login password 'CHANGE_ME_BEFORE_RUNNING';
  end if;
end $$;
alter role smartbiz_ai set default_transaction_read_only = on;
alter role smartbiz_ai set statement_timeout = '5s';
grant usage on schema public to smartbiz_ai;
grant select on public.customers, public.suppliers, public.products, public.expenses, public.orders,
  public.order_items, public.payments, public.order_balances, public.customer_dues, public.low_stock
  to smartbiz_ai;
do $$ declare t text; begin
  foreach t in array array['customers','suppliers','products','expenses','orders','order_items','payments'] loop
    execute format('drop policy if exists ai_read on public.%I', t);
    execute format('create policy ai_read on public.%I for select to smartbiz_ai using (true)', t);
  end loop;
end $$;
